# Generated by Django 5.2.3 on 2025-06-13 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_driver_is_available_vehicle_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 13, 12, 29, 4, 467667)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Delivered", "Delivered"),
                    ("Delayed", "Delayed"),
                ],
                default="In Progress",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="review_created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
